DefaultContentLanguage = "en"
Paginate = 8
PaginatePath = "page"
baseURL = "/"
copyright = "Taiwan Employment Gold Card Office"
defaultContentLanguageInSubdir = true
disableAliases = true
disableHugoGeneratorInject = false
disableKinds = ["RSS"]
disableLanguages = []
enableInlineShortcodes = true
ignoreErrors = ["error-disable-taxonomy"]
pygmentsUseClasses = true
relativeURLs = false
title = "Taiwan Gold Card"
[taxonomies]
category = "categories"
topic = "topics"
tag = "tags"
badge = "badges"
subtag = "subtags"

[Params]
loadFromCDN = "true"

[permalinks]
gallery = "/gallery/:year/:month/:slug/"

[languages]

[languages.en]
languageName = "English"
title = "Taiwan Gold Card"
weight = 1
[languages.en.params]
linkedin = "https://www.linkedin.com/company/taiwangoldcard/"
ndc_website = "https://www.ndc.gov.tw/en/"
apply = "/en/apply/"
phone = "+886 2-7733-7660"
email = "help@taiwangoldcard.tw"

[languages.zh]
languageName = "中文"
title = "台灣就業金卡"
weight = 2
[languages.zh.params]
linkedin = "https://www.linkedin.com/company/taiwangoldcard/"
ndc_website = "https://www.ndc.gov.tw/default.aspx"
apply = "/zh/apply/"
phone = "+886 2-7733-7660"
email = "help@taiwangoldcard.tw"

[imaging]
anchor = "center"

# [languages.de]
# disableKinds = ["404", "taxonomy", "sitemap"]
# languageName = "Deutsch"
# title = "Taiwan Gold Card"
# weight = 10
# [languages.de.outputs]
# home = ["WELCOME"]

# [languages.es]
# disableKinds = ["404", "taxonomy", "sitemap"]
# languageName = "Español"
# title = "Taiwan Gold Card"
# weight = 10
# [languages.es.outputs]
# home = ["WELCOME"]

# [languages.ar]
# disableKinds = ["404", "taxonomy", "sitemap"]
# languageName = "عربى"
# title = "Taiwan Gold Card"
# weight = 10
# [languages.ar.outputs]
# home = ["WELCOME"]

[markup]
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 1

[minify]
disableCSS = true
disableHTML = false
disableJS = true
disableJSON = false
disableSVG = false
disableXML = false
minifyOutput = true
[outputs]
home = ["HTML", "MANIFEST", "SEARCH"]
page = ["HTML"]
term = ["HTML", "DATA"]
[outputFormats.manifest]
baseName = "manifest"
mediaType = "application/json"
name = "manifest"
notAlternative = "true"
permalinkable = "true"
[outputFormats.data]
baseName = "data"
mediaType = "application/json"
name = "data"
notAlternative = "true"
permalinkable = "true"
[outputFormats.search]
baseName = "search"
mediaType = "application/json"
name = "search"
notAlternative = "true"
permalinkable = "true"
# [outputFormats.welcome]
# baseName = "welcome"
# mediaType = "application/json"
# name = "welcome"
# notAlternative = "true"
# permalinkable = "true"
# [outputFormats.data]
# baseName = "data"
# mediaType = "application/yaml"
# name = "data"
# notAlternative = "true"
# permalinkable = "true"
